language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - pypy
install:
  - pip install .
  - pip install coveralls
script:
  - coverage run --source flask_basicauth setup.py test
  - coverage report -m
after_script:
  - coveralls --verbose
